const express=require('express');
const router=express.Router();
const path=require('path');
const shopController=require('../controllers/shop');
router.get('/',shopController.getIndex);
router.get('/products',shopController.getProducts);
router.get('/product-detail/:id',shopController.getProduct);
router.get('/cart',shopController.getCart);
router.post('/cart',shopController.postCart);
router.get('/cart-delete-item/:id',shopController.getCartDeleteItem);
router.get('/orders');
router.get('/checkout',shopController.getCheckout);
module.exports=router;